### PR TITLE
Adding an undo and redo button(WITH CODE NOW)

### PR DESCRIPTION
**Pull request by Zzisx**
2 different methods, pick which one is best for you-

MEMENTO METHOOD:

const mementos = []
const input = document.querySelector('input')

function saveMemento() {
  mementos.push(input.value)
}

function undo() {
  const lastMemento = mementos.pop()
   
  input.value = lastMemento ? lastMemento : input.value
}

COMMAND PATTERN: 

const commands = []
const input = document.querySelector('input')

function saveCommand(e) {
  commands.push({
    // the action is also saved for implementing redo, which
    // is not implemented in this example.
    action: { type: 'add', key: e.key, index: input.selectionStart },
    inverse: { type: 'remove', index: input.selectionStart }
  })
}

function undo() {
  let value = input.value.split('')
  const lastCommand = commands.pop()
 
  if (!lastCommand) return
    
  switch (lastCommand.inverse.type) {
    case 'remove':
      value.splice(lastCommand.inverse.index, 1)
      break;      
  }
  
  input.value = value.join('')
}

<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

**Comment by lovasoa** [comment]
Hello ! 
  This is not a valid pull request. This pull request does not contain an implementation of the feature. If this is a feature request, you can open an issue instead of a pull request.

**Comment by Zzisx** [comment]
Oh ok will thanks for letting me know, I'm new sorry.

**Comment by lovasoa** [comment]
no problem! If you are interested in implementing this feature in wbo yourself, you can do it and open a pull request with the actual implementation.

**Comment by Zzisx** [comment]
Ok! I will attempt. I know a little bit of coding but I'm still learning (:
What language WBO written in?

**Comment by lovasoa** [comment]
javascript

**Pull request closed without merging**
