### PR TITLE
Default `en` then alphabetically, `hu` locale, tidy-ups

### PR DESCRIPTION
**Pull request by ovari**
<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

**Comment by ovari** [comment]
* Added `hu` (magyar - Hungarian)
* github > GitHub
* no space before an exclamation mark (!) in `en`
* 1-character ellipsis
* opensource > open-source

Please accept. Thank you

**Comment by lovasoa** [comment]
Thank you for your contribution, @ovari !

**Comment by ovari** [comment]
You're welcome @lovasoa.

1. Instead of having one file `translations.json` with all the locales, can you make one file per locale?
* This would make it easier to translate as translators can copy the `en.json` and create another file like `hu.json`.
* It would also make it easier to see what locales are currently available as each language would have a filename.
2. Can language `en` be changed to `en-US`? `Color` should be `Colour` for `en-GB`?

Thank you once again

**Comment by ovari** [comment]
Can the `Go` button label please be translatable?

**Comment by lovasoa** [comment]
@ovari : I created a new issue to track progress on your suggestions. All of them seem reasonable to me. I'm going to comment on the issue with pointers on how to implement them so that you can make a pull request if you are interested.

**Comment by ovari** [comment]
Clicking [Nyilvános tábla megnyitása](https://wbo.ophir.dev/boards/anonymous), at https://wbo.ophir.dev/?lang=hu, opens https://wbo.ophir.dev/boards/anonymous. Unfortunately, hovering above the `Pencil` icon on the left the label is shown in `en` not `hu`.

Clicking on [Gehe zum öffentlichen Whiteboard](https://wbo.ophir.dev/boards/anonymous), at https://wbo.ophir.dev/?lang=de, opens https://wbo.ophir.dev/boards/anonymous. Unfortunately, hovering above the `Pencil` icon on the left the label is shown in `en` not `de`.

Can you reproduce and please fix?

Thank you once again

**Comment by lovasoa** [comment]
> Clicking Nyilvános tábla megnyitása, at https://wbo.ophir.dev/?lang=hu, opens https://wbo.ophir.dev/boards/anonymous. 
> Unfortunately, hovering above the Pencil icon on the left the label is shown in en not hu.

This is because your browser is in english. A hungarian user with their operating system in hungarian will see both https://wbo.ophir.dev/ and https://wbo.ophir.dev/boards/anonymous in hungarian, without having to do anything. I am reluctant to setting the language parameter of the URL of whiteboard pages in the links from the main page, because these URLs are what then gets shared. We wouldn't want to hardcode the language of the page for all the people with whom the board will be shared. I do however agree that the current behavior is unintuitive. A better solution would be to set a *preferred language* cookie when the user explicitly chooses a language. I am adding that to #104.

**Comment by ovari** [comment]
Can you add the language drop-down to the whiteboard too?

Whether the locale drop-down is at the bottom (as shown in the image) or the top-right (consistent with the main page)?

image

What do you think?

Thank you

**Comment by lovasoa** [comment]
We can do that, preferably on the top right as the toolbar is already too large for small screens.

**Comment by ovari** [comment]
Yes, unfortunately all the buttons don't show on our screen.
image

**Comment by ovari** [comment]
@lovasoa are you able to advise when https://github.com/lovasoa/whitebophir/commit/d808412eb90290813921b01442c0963936fb75f5 will be live at https://wbo.ophir.dev/? Thank you

**Comment by lovasoa** [comment]
I deployed it

**Comment by ovari** [comment]
> I deployed it

Strange, https://wbo.ophir.dev/?lang=hu is still showing without the https://github.com/lovasoa/whitebophir/commit/d808412eb90290813921b01442c0963936fb75f5 updates.

The website shows L157, i.e. `collaborative_whiteboard`, as `Együttműködő tábla` not `Együttműködési tábla`.
image

All the other updated strings seems to not be showing either.

Thank you once again

**Comment by lovasoa** [comment]
Hello, thanks for telling me about this. We had an issue on the production server and the update failed.

**Pull request merged**
