### PR TITLE
Move

### LINKED ISSUE #10: Possibility to edit / move entities
Currently: if I want to modify an entity, I must delete the current one and create a new one. It's ok for basic entities, but as soon as my schema is made of several entities, it will be complicated.

Expected: allow to modify an entity. The minimum would be to be able to move an entity.

This would be a required feature for us to integrate the tool in tracim as a dedicated app

### PR DESCRIPTION
**Pull request by lovasoa**
Add an element mover
Original PR by @paolobolzoni  (see #86)

Fixes #10

### CODE REVIEW

**Comment by lovasoa** [comment]
I removed the move_all functionnality, because I'd rather avoid features that let a single user have an effect to the whole board. A single misbehaving user could prevent everyone else from working constructively. 
However, I do understand that the feature may be useful. I think implementing #85 would solve the root problem.

**Comment by paolobolzoni** [comment]
Of course I am well aware that it is your project and your is the final word, but I have few comments.

Indeed to have an unlimited canvas (ie, #85) would solve the root problem better than move-all, but wouldn't be better to remove move-all after #85 is implemented? It is really annoying to start a drawing in the top right and notice you run out of space after a while for you need to add something on the right or on the top.

In my implementation the tool moves the first shape the cursor touches clicking or after while dragging. So a user does not need to do a pixel-perfect click to move small objects like thin lines or dots. The current implementation is simpler, but in this case I think a bit more implementation complexity was a good exchange for user experience: click and if you missed just drag a bit until the mover picks up the intended shape.

In the mover.js stopMoving function you just call move. However the move function broadcasts the shape position only every 70 milliseconds. Are you sure the final position is sent? Perhaps one needs to reset last_sent to 0 or something similar?

**Comment by lovasoa** [comment]
Hello, and thank you for your feedback. These are only good points you are raising. To answer them:
  - A move-all tool would let a single bad actor waste the experience of all the other connected users. So I thought it would be better not to have it, even before #85. 
 - When I noticed this *hover to select* behavior, I thought it was a bug. I think many users would have taken it as a bug too. This behavior is uncommon in drawing apps, and not very discoverable... But if there is demand, we'll reintroduce it! In the meantime, you can just zoom on a small element to select it. 
 - About the 70ms threshold in release: good point. Did you notice any issue with it? We've had the same kind of issues in other tools, and I think we should handle the throttling in board.js.

**Comment by paolobolzoni** [comment]
That's a fair point. I used the board only with my friends, but rogue users probably do exists in other scenarios. Still, is it really so much worse of someone dragging around the Eraser?

The hover to select was indeed intentional, but I guess the commit message where I wrote "_The mover not detect the object to move_" instead of "_The mover no**w** detect**s** the object to move_" has been very confusing (I was probably sleepy).
Still, I hardly believe it worsen the user experience, it is also hard to compare with other drawing applications as whitebophir has no concept of selection. My limited testing with friends did not bring anyone confused, they simply did not notice the possibility as they naturally tried to click on the shapes, but seldom pick up the correct shape after starting moving. I even received a positive feedback once one understood how it worked. Still, as I said, it has been quite limited testing.
About other drawing apps, I think to press the middle button should automatically use the Hand tool as in Qcad, Gimp, Inkscape, and probably many others.

About the 70ms, I did not test your version deeply, but when I was implementing I noticed it could happen that the user moving and all other users end up with shapes in different positions. It could also happen that reloading would move shapes slightly (as the server never got the final position).
The solution is pretty easy, though. Ensure to send the final position when the user stop moving. Since all positions are absolute, there cannot be confusion. Even if two users start moving the same object at the same time, only one position will "win."

**Pull request merged**
