### PR TITLE
Update translations.json

### PR DESCRIPTION
**Pull request by Lexaul**
update language for Chinese_traditional
<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

**Comment by lovasoa** [comment]
Hello, and thank you for your contribution. 

The state of our current Chinese translation is not great; it is partly computer generated. 

I don't know much about Chinese languages. Would it be possible to replace the current (bad) Chinese translation by yours, or wouldn't it be understandable in mainland China?

**Comment by lovasoa** [comment]
Also, isn't "Recent boards" translatable ?

**Comment by Lexaul** [comment]
Hello lovasoa ,bonjour.

China (zh-cn), Singapore(zh-sg) use Simplified Chinese, known as zh-hans,
Taiwan(zh-tw), Hongkong(zh-hk) use Traditional Chinese, also known as zh-hant.

I suggest keeping both current zh version(zh) and mine(zh-TW).
Meanwhile, I'll change the current zh tag to zh-CN for mainland and zh-hans users.

and yes, "Recent boards" can be translate, I'll cancel this commit and re-commit after I fix it.

Thank you for this perfect project, you (your team) are awesome.

**Comment by Lexaul** [comment]
done fixing known issue :)

**Comment by Lexaul** [comment]
Hello,

We've integrate WBO into jitsimeet, works fine but there are no security options such as password auth.
Hope that there is a feature of protecting private whiteboards in the future.

Screenshot from a friend.
image

Thanks again for creating this wonderful project, hope you have a great day
and Im looking forward to the upcoming translation update
If there is anything I can help, please let me know :)

**Comment by jasoncheng7115** [comment]
> Thanks again for creating this wonderful project, hope you have a great day
> and Im looking forward to the upcoming translation update
> If there is anything I can help, please let me know :)

Thanks to @Lexaul for translating Traditional Chinese!

**Comment by lovasoa** [comment]
Sorry for the delay, and thanks again for your contribution,  @Lexaul !

**Comment by lovasoa** [comment]
I fixed a problem in the language matching logic, and deployed the result to https://wbo.ophir.dev

If you set your browser to taiwanese, WBO should display the zh-TW translation by default, now.

**Pull request merged**
