### PR TITLE
bugfix whipe board with new role function.

### PR DESCRIPTION
**Pull request by holema**
<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

**Comment by holema** [comment]
This PR fixes, that is is not possible to whipe the board after our refactoring of the jwt

**Comment by lovasoa** [comment]
roleInBoard returns a string, not a boolean. Can you add a test?

**Comment by holema** [comment]
I add the comparisation with the string moderator.
I don´t know how to write a test for this function. Propably I can do this during this week.

**Comment by holema** [comment]
Hello @lovasoa,
I think I don´t have any time to create a test. 
But the fix works now and cleans the whiteboard when you have moderator rights.

**Comment by holema** [comment]
Hello @lovasoa,
Are you giong to merge this PR? This Bug is realy sad

**Comment by lovasoa** [comment]
Hey, sorry for the long delay. It's merged

**Comment by holema** [comment]
Hello @holema,
thanks for merging the PR.
I just saw, that the docker image is not rebuild with the fix.
Best regards

**Comment by lovasoa** [comment]
I just published v1.19.1 : https://hub.docker.com/repository/docker/lovasoa/wbo/tags?page=1&ordering=last_updated

**Pull request merged**
