### PR TITLE
Update translations.json with "ca" language

### PR DESCRIPTION
**Pull request by jbatlleb**
Added Catalan translation (lang="ca", "ca-es") to translations.json.
The translation is complete.

<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

### CODE REVIEW

**Comment by lovasoa** [comment]
@jbatlleb : thanks ! It looks like there is a formatting issue in the translations file

**Comment by jbatlleb** [comment]
I checked the file and couldn't locate any format errors...
Is there any other information I could get in order to adress the issue?
Thanks.

**Comment by lovasoa** [comment]
You can format the file with `npx prettier`

**Review by jbatlleb — COMMENTED** [review]
Catalan translation's format in translations.json,

**Comment by lovasoa** [comment]
Thank you for your contribution, it's included !

**Pull request merged**
